export const STRINGS = {
  en: {
    appTitle: 'ArogyaAI',
    whatAreYouFeeling: 'What are you feeling?',
    searchPlaceholder: 'Search symptoms...',
    vitalsLabel: 'Vitals (optional)',
    riskFactorsLabel: 'Risk factors (optional)',
    temperatureLabel: 'Temperature (°C)',
    pulseLabel: 'Pulse (bpm)',
    breathingLabel: 'Breathing rate (per min)',
    ageLabel: 'Age',
    sexLabel: 'Sex',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    assess: 'ASSESS',
    disclaimer: 'This is not a diagnosis. This is not a medical device. It does not replace a doctor.',
    online: 'Online',
    offline: 'Offline',
    riskFactorLabels: {
      diabetes: 'Diabetes',
      hypertension: 'Hypertension',
      heart_disease: 'Heart disease',
      pregnancy: 'Pregnancy',
      smoking: 'Smoking',
      age_60_plus: 'Age 60+',
    },
    tierBanner: {
      EMERGENCY: 'EMERGENCY',
      URGENT: 'URGENT — see a doctor today',
      ROUTINE: 'ROUTINE — manage at home',
    },
    safetyRuleNotice: (ruleId) => `Safety rule ${ruleId} · model not used`,
    becauseYouReported: (symptomList) => `Because you reported ${symptomList}`,
    and: 'and',
    possibleCauses: 'Possible causes',
    whyRankedLower: '▸ Why ranked lower?',
    startOver: 'Start over',
    alsoCommon: 'Also common:',
  },
  hi: {
    appTitle: 'ArogyaAI',
    whatAreYouFeeling: 'आपको क्या महसूस हो रहा है?',
    searchPlaceholder: 'लक्षण खोजें...',
    vitalsLabel: 'महत्वपूर्ण संकेत (वैकल्पिक)',
    riskFactorsLabel: 'जोखिम कारक (वैकल्पिक)',
    temperatureLabel: 'तापमान (°C)',
    pulseLabel: 'नाड़ी (bpm)',
    breathingLabel: 'सांस की दर (प्रति मिनट)',
    ageLabel: 'उम्र',
    sexLabel: 'लिंग',
    male: 'पुरुष',
    female: 'महिला',
    other: 'अन्य',
    assess: 'जांच करें',
    disclaimer: 'यह निदान नहीं है। यह चिकित्सा उपकरण नहीं है। यह डॉक्टर की जगह नहीं ले सकता।',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    riskFactorLabels: {
      diabetes: 'मधुमेह',
      hypertension: 'उच्च रक्तचाप',
      heart_disease: 'हृदय रोग',
      pregnancy: 'गर्भावस्था',
      smoking: 'धूम्रपान',
      age_60_plus: '60+ आयु',
    },
    tierBanner: {
      EMERGENCY: 'आपातकाल',
      URGENT: 'तत्काल — आज डॉक्टर को दिखाएं',
      ROUTINE: 'सामान्य — घर पर देखभाल करें',
    },
    safetyRuleNotice: (ruleId) => `सुरक्षा नियम ${ruleId} · मॉडल का उपयोग नहीं हुआ`,
    becauseYouReported: (symptomList) => `क्योंकि आपने बताया: ${symptomList}`,
    and: 'और',
    possibleCauses: 'संभावित कारण',
    whyRankedLower: '▸ कम रैंक क्यों?',
    startOver: 'फिर से शुरू करें',
    alsoCommon: 'यह भी सामान्य है:',
  },
};
